### ISSUE TITLE
Compiling snips nlu for Windows

### ISSUE THREAD

**Issue by sprobst** [BobLd/SnipsNlu#1]
Hello,

I know this is an old repository, but I'll try it anyway. 

I tried to compile snips-nlu-rs on Windows, added the [lib] section and crate_type to Cargo.toml. I installed llvm through Chocolatey package manager. It build successfully, but the resulting .dll was around 11KB in size. This seems way too small compared to the 25MB in this repo. What could be the issue? Are there more steps involved in building a .dll?

**Comment by BobLd** [comment]
Hi @sprobst, sorry I missed your issue - I didn't received a notification.

 Do you still have the issue? If yes, I'll try to take some time to have a look on my side

**Comment by sprobst** [comment]
I somehow managed to get it to compile to a larger file. If I remember correctly, I had to change the library type to `dylib`

**Comment by GeorgeS2019** [comment]
@sprobst @BobLd 

There is a newer and faster version of crfsuite-rs
https://github.com/messense/crfs-rs

Is it worth updating SnipsNlu?
